# Generated by Django 2.2.7 on 2020-05-16 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='studentavar.png', upload_to='students')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=6, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
    ]
